config/routes.rb
Rails.application.routes.draw do

  get 'profiles/index'
  get 'profiles/friend'

  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/help'

  get 'todos/index'
  get 'todos/friends'
  post 'todos/create' => 'todos#create'
  post 'todos/createPhoto' => 'todos#createPhoto'
  post 'todos/friendPhotos' => 'todos#friendPhotos'
  post 'todos/findLocation' => 'todos#findLocation'
  post 'login' => 'static_pages#login'

  root 'static_pages#home'

end

app/views/layouts/_todos.html.erb
		<!--Font-->
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>

		<!--Navigation Bar-->
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a href="/todos/index"><img class="home-icon" src='<%= asset_path "logo-with-name-white.png" %>'></a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		      	<li class="<%= "active" if params[:action] == "index" && params[:controller] == "todos" %>">
		      		<!-- <label><span class="glyphicon glyphicon-globe"></span></label> -->
		      		<%= link_to "TravelDex", todos_index_path%>
		      	</li>
		        
		        <li class="<%= "active" if params[:action] == "friends" && params[:controller] == "todos" %>">
		        	<!-- <label><span class="glyphicon glyphicon-comment"></span></label> -->
		        	<%= link_to "Friends", todos_friends_path%>
		        </li>
		      </ul>
		    
		      <ul class="nav navbar-nav navbar-right">
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> Me <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><%= link_to "Profile", profiles_index_path%></li>
		            <li><a href="#">Blog</a></li>
		            <li><a href="#">Settings</a></li>
		            <li class="divider"></li>
		            <li><a href="http://mysterious-atoll-6223.herokuapp.com/" onclick="logout();">Log out</a></li>
		          </ul>
		        </li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
	<head>
		<!--script type="text/javascript" src="http://malsup.github.io/jquery.cycle.lite.js"></script-->
		<%= javascript_include_tag	"application", media: "all", "data-turbolinks-track" => true %>
		<!--IMPORTANT: include Bootstrap files after jQuery files due to some file conflicts-->
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<!--IMPORTANT: ensures custom CSS files have priority-->
		<!--ensures controller specific pages have different stylesheets-->
		<%= stylesheet_link_tag   "application", params[:controller], media: "all", "data-turbolinks-track" => true %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div id="fb-root"></div>
		<script>
			function logout() {
				FB.logout(function() {
					//document.location.reload();
					<% session.clear %>
					window.location = "http://mysterious-atoll-6223.herokuapp.com/";//----------LOGOUT IS BUGGY
				});
			}
		</script>

		<script>
		window.fbAsyncInit = function() {
			  FB.init({
				 appId      : '1554632284756058',
				 cookie     : true,  // enable cookies to allow the server to access 
											// the session
				 xfbml      : true,  // parse social plugins on this page
				 version    : 'v2.1' // use version 2.1
			  });
				jQuery(document).trigger('FBSDKLoaded');
		  };
		
		  // Load the SDK asynchronously
		  (function(d, s, id) {
			 var js, fjs = d.getElementsByTagName(s)[0];
			 if (d.getElementById(id)) return;
			 js = d.createElement(s); js.id = id;
			 js.src = "//connect.facebook.net/en_US/sdk.js";
			 fjs.parentNode.insertBefore(js, fjs);
		  }(document, 'script', 'facebook-jssdk'));

			$.ajaxSetup({
			  beforeSend: function(xhr) {
				 xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'));
			  }
			}); 
		</script>
		<!--show specific content of the page-->
		<%= yield %>
	</body>
</html>